language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run cov
env:
  global:
    # TOKEN
    - secure: ZdTWw0qME8mXOUCTVm/3LqFFIe6OOkYQeP3bOUw3pONPy1itN1PK+rSgkELBa1ZewlkyiHkt3oLdFjdhdUx7HEA8D3Q6ax5dAJ0V4Kv3WTB24HyJwOqQOtb1r1as+QUSCLv7wZeblubKunkguE+zIbSAwDEx3urFXYdZ8dqKuBoCYnHhSTvMiEfVTlIZZ/OjqyteZEYyE7iQpIrYCjjD/9FCoVPvtXuNK5Vg3K3EyZ7c7wTDnss20wxvHyV9ehT+a/0hJ29qFMcY/x6yR6a6Wqib/jjFbn+LlkkdlY6ianGPEVGLa/jWoW1YTcwOupk98pHtoeJFE1Hq5xK/eAxo2x5auw/h01LtcY88Mcg79TKpXxAJRZxptRvNie1gpzYlQCWvD0MSxh3O+ZhYNI+DSaijIdudWCAu2rfgFZL6zd1uLknaFt0WiLeUudFzwcCvIeYNtov07H+rFWHs8q9bCyJ/ZAHGRw5VXU6iqJ/O5XI0whknXDYprZvQgemZIoWVGJRPZbuMS7jG8Y4kghhRgB6HWaLIkMmDDMjL+cGnwgjUJmtY/0/NWnux8G/YNKUWdmiVTLuXM82YjxiWbbWnA7c19xOQTCF0TdPAuGrKakhAjUza3i9+MwR+LbvEqYY+2aIAKhr3wBsy6kdl/mjqy7e4dFPJ4GI70fAw/4Qpp4c=
    # SECRET
    - secure: T4GxbZPW+ypnG42y2n0ODB1II8dSEtaXsr1RKgdmV/n9Aj5OAFI0CMMFLNsferDFbZatY5zJ+jscMiBy0d0EC3miq3DwcRLw/zLXmTp7WCE75fCxdy4wqxkqIchzP9287o5iydszjQY/VeGviC+s+YngP9ZZ9d96JhwV3G53Kj80xrFCwJdDGa7vF+tupXwmRnrEBk7nz471ZA7SpoLcvupA9I9WfsnLAYQV/RILoLjCPyUVcjzHzKlNbnofe+eV8QuF2ONZ59KBN+r0kmUSX8/hhTuHgbsbkSwA4+agYLtPdT/DHZtDp8fSnyaJ80KicbaoBetl4q+XsdJEn49ksWR7N+sFEf8MLhw1Sx7ePG6rVfwab2o2GKMMBkb14Vd1GEX5FpML8nFfKiFUAhTJ8L/sEE/nsCM6EeLC8GrG+0PuOlg1Mu4iP8GNTFY9Ip8P4yI+U0tTvR/H536rSemG1Q68Pnv/7Uz7vJeogOSnG2Wbt2dM98b24JUf0GqI8FBgk67yx5lc57gR3dIk1v+OpyBxLfpCf2SPXULjVWL1VNnURg67o4sC/WN3glPHyM/T13npNJnqusPJnGk4rQOEksfb9hPYh1JH8gPWPU3mBfIEKfomlzze3FKc6WKZYYOjc9kxbubAP9NANiSNlDkwi7agpKca6rV84rxtssLzZJA=
